[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml",
]

[window]
decorations = "None"
padding = { x = 0, y = 1 }
dynamic_padding = true
opacity = 1.0

[window.dimensions]
columns = 140
lines = 90

[window.position]
x = 0
y = 0

[font]
size = 12

[font.offset]
x = 0
y = 0

